import os

IS_PRODUCTION = os.getenv("IS_PRODUCTION", "false") == "true"
IS_DEVELOPMENT = not IS_PRODUCTION
AUTH_API_KEY = os.getenv("AUTH_API_KEY")

# DATABASE
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_DB = os.getenv("POSTGRES_DB")

SQLALCHEMY_URI = (
    f"postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}" # noqa
)
